name: ChatManager
main: ru.tehkode.chatmanager.bukkit.ChatManager
depend: [ PermissionsEx ]
version: 1.15
author: t3hk0d3
website: www.bukkit.org
description: Chat management plugin from PermissionsEx
